/* ============================================================
   Theme runtime — applies the agency's DESIGN OVERRIDES to every
   screen and popup: CSS-variable values, per-element style rules
   and text replacements.

   This small file SHIPS with the game. The visual editor itself
   (js/designer.js — the "Design Studio") is agency-only: it loads
   solely via the secret ?design=agency URL and is stripped from
   every build, so the restaurant receives a locked game.

   Sources, in order:
   1. window.DESIGN_OVERRIDES — the baked design exported from the
      Design Studio (js/design-overrides.js).
   2. A localStorage DRAFT — only in design mode, so the agency can
      edit live and export when happy.
   ============================================================ */

const Theme = (() => {
  const DRAFT_KEY = 'ffn_design_draft_v1';
  const DESIGN_MODE =
    new URLSearchParams(location.search).get('design') === 'agency';

  const clone = (o) => JSON.parse(JSON.stringify(o || {}));
  const normalize = (o) => Object.assign({ vars: {}, css: {}, text: {} }, clone(o));

  let overrides = normalize(window.DESIGN_OVERRIDES);
  if (DESIGN_MODE) {
    try {
      const d = localStorage.getItem(DRAFT_KEY);
      if (d) overrides = normalize(JSON.parse(d));
    } catch {}
  }

  // ---- CSS: one injected stylesheet rebuilt on every change ----------
  let styleEl = null;
  function cssText() {
    let out = '';
    // !important so var overrides beat applyBrand()'s inline styles on <html>.
    const vars = Object.entries(overrides.vars);
    if (vars.length) out += ':root{' + vars.map(([k, v]) => `${k}:${v} !important`).join(';') + '}\n';
    for (const [sel, props] of Object.entries(overrides.css)) {
      const body = Object.entries(props).map(([p, v]) => `${p}:${v} !important`).join(';');
      if (body) out += `${sel}{${body}}\n`;
    }
    return out;
  }
  function applyCss() {
    if (!styleEl) {
      styleEl = document.createElement('style');
      styleEl.id = 'ffn-theme';
      document.head.appendChild(styleEl);
    }
    styleEl.textContent = cssText();
  }

  // ---- Text: re-applied whenever the DOM re-renders -------------------
  // (screens rebuild their innerHTML; I18N.apply rewrites data-i18n text)
  // A guard flag stops the observer reacting to its own writes.
  let applying = false;
  function applyText() {
    applying = true;
    for (const [sel, txt] of Object.entries(overrides.text)) {
      try {
        document.querySelectorAll(sel).forEach((el) => {
          if (el.textContent !== txt) el.textContent = txt;
        });
      } catch {}
    }
    applying = false;
  }
  let moTimer = null;
  const mo = new MutationObserver(() => {
    if (applying) return;
    clearTimeout(moTimer);
    moTimer = setTimeout(applyText, 60);
  });

  function saveDraft() {
    if (!DESIGN_MODE) return;
    try { localStorage.setItem(DRAFT_KEY, JSON.stringify(overrides)); } catch {}
  }
  function applyAll() { applyCss(); applyText(); }

  function boot() {
    applyAll();
    mo.observe(document.body, { childList: true, subtree: true, characterData: true });
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);
  else boot();

  return {
    DESIGN_MODE,
    get: () => clone(overrides),
    /** Replace the whole override set (designer import / reset). */
    set(o) { overrides = normalize(o); applyAll(); saveDraft(); },
    setVar(name, value) {
      if (!value) delete overrides.vars[name];
      else overrides.vars[name] = value;
      applyAll(); saveDraft();
    },
    setRule(sel, prop, value) {
      const r = overrides.css[sel] || (overrides.css[sel] = {});
      if (!value) delete r[prop]; else r[prop] = value;
      if (!Object.keys(r).length) delete overrides.css[sel];
      applyAll(); saveDraft();
    },
    setText(sel, txt) {
      if (!txt) delete overrides.text[sel];
      else overrides.text[sel] = txt;
      applyAll(); saveDraft();
    },
    rulesFor(sel) { return clone(overrides.css[sel] || {}); },
    textFor(sel) { return overrides.text[sel] || ''; },
    clearElement(sel) {
      delete overrides.css[sel]; delete overrides.text[sel];
      applyAll(); saveDraft();
    },
    /** Discard the draft and go back to the baked design. */
    reset() {
      overrides = normalize(window.DESIGN_OVERRIDES);
      applyAll();
      try { localStorage.removeItem(DRAFT_KEY); } catch {}
    },
    /** Contents for js/design-overrides.js — bake into the build. */
    exportFile() {
      return '/* Generated by the Pasta Ninja Design Studio — do not edit by hand.\n' +
             '   This is the shipped design; theme.js applies it at boot. */\n' +
             'window.DESIGN_OVERRIDES = ' + JSON.stringify(overrides, null, 2) + ';\n';
    },
  };
})();
